-- 创建用户表
create table public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 启用行级安全性（RLS）
alter table public.users enable row level security;

-- 创建策略允许匿名访问
create policy "允许匿名用户查看" on users
  for select
  to anon
  using (true);

create policy "允许注册用户创建" on users
  for insert
  to authenticated
  with check (true);

create policy "允许用户更新自己的记录" on users
  for update
  using (auth.uid() = id);

create policy "允许用户删除自己的记录" on users
  for delete
  using (auth.uid() = id);

-- 创建触发器自动更新 updated_at
create function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

create trigger on_users_updated
  before update on public.users
  for each row
  execute procedure public.handle_updated_at();

-- 添加注释
comment on table public.users is '用户表';
comment on column public.users.id is '用户ID';
comment on column public.users.name is '用户名';
comment on column public.users.email is '邮箱地址';
comment on column public.users.created_at is '创建时间';
comment on column public.users.updated_at is '更新时间';